Move User class from UserAuthenticationTests
DVT/ShowcaseiOS pull request #4
Opened 2018-04-20 11:43 UTC by VaalSquared

--> Created a seperate file for the User class

2018-04-21 12:14 UTC, pjwelcome requested changes

2018-04-21 12:14 UTC, pjwelcome commented on Showcase-iOSTests/Login/Service/UserAuthenticationTests.swift
>      enum AuthError: Error {
This Enum also does not belong in the tests please move this also

2018-04-23 11:41 UTC, pjwelcome commented
@VaalSquared check there is merge conflicts. Please fix this.

2018-04-23 11:42 UTC, pjwelcome submitted a review, later dismissed

2018-04-23 12:30 UTC, Slavitor approved these changes

2018-04-23 13:01 UTC, merged