Feature/detail view
DVT/ShowcaseiOS pull request #51
Opened 2018-05-25 14:05 UTC by edward-mtsh

Added detail view

2018-05-25 18:29 UTC, vincent-coetzee commented
Hi Guys

Can you please remove me from this repo ?

Thanks


> On 25 May 2018, at 16:05, Edward <notifications@github.com> wrote:
> 
> Added detail view
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/DVT/ShowcaseiOS/pull/51 <https://github.com/DVT/ShowcaseiOS/pull/51>
> Commit Summary
> 
> Adding ContactUsCollectionViewCell,adding Popping font
> "Adding contactUS collectionView cell, collectionViewCell viewModel, contactUsDelegate protocol.
> Merge Conflict Resolution
> Adding contactUsCollectionViewCell and swift class.
> Adding computed properties and shared applicationDelegate property. Removing map related code. Adding ContactUsCellViewModelTests.
> Removing navigate method. Adding sharedApplicationDelegate and implementation.
> Adding KingFischer Pod.
> Merge Conflict Resolution.
> Updating run script
> Merge conflict resolution.
> Adding App detail view subviews
> Updating constraint
> Merge conflict resolution when merging develop in.
> Adding Subviews.
> Adding styling
> Added detail view
> Updated detail view with protocol
> File Changes
> 
> M Podfile.lock <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-0> (107)
> M Showcase-iOS.xcodeproj/project.pbxproj <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-1> (101)
> A Showcase-iOS/Dashboard/DetailView/FunctionalityView/FunctionalityView.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-2> (37)
> A Showcase-iOS/Dashboard/DetailView/FunctionalityView/FunctionalityView.xib <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-3> (50)
> A Showcase-iOS/Dashboard/DetailView/MainDetailSubView/MainDetailView.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-4> (58)
> A Showcase-iOS/Dashboard/DetailView/MainDetailSubView/MainDetailView.xib <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-5> (83)
> A Showcase-iOS/Dashboard/DetailView/ScreenshotView/ScreenshotCollectionViewCell.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-6> (32)
> A Showcase-iOS/Dashboard/DetailView/ScreenshotView/ScreenshotCollectionViewCell.xib <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-7> (43)
> A Showcase-iOS/Dashboard/DetailView/TechnologyView/TechnologyView.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-8> (37)
> A Showcase-iOS/Dashboard/DetailView/TechnologyView/TechnologyView.xib <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-9> (50)
> M Showcase-iOS/Dashboard/Presenter/HomePresentable.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-10> (1)
> M Showcase-iOS/Dashboard/Presenter/HomePresenter.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-11> (9)
> M Showcase-iOS/Dashboard/View/HomeViewController.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-12> (5)
> A Showcase-iOS/Dashboard/View/ShowcaseAppDetailViewController.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-13> (78)
> M Showcase-iOS/DependencyContainer/DependencyContainer.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-14> (5)
> M Showcase-iOS/Home.storyboard <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-15> (124)
> M Showcase-iOS/Info.plist <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-16> (4)
> A Showcase-iOS/Router/Wireframe.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-17> (27)
> A Showcase-iOS/Router/WireframeDelegate.swift <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-18> (14)
> A Showcase-iOS/Utils/Poppins-Medium.otf <https://github.com/DVT/ShowcaseiOS/pull/51/files#diff-19> (0)
> Patch Links:
> 
> https://github.com/DVT/ShowcaseiOS/pull/51.patch <https://github.com/DVT/ShowcaseiOS/pull/51.patch>
> https://github.com/DVT/ShowcaseiOS/pull/51.diff <https://github.com/DVT/ShowcaseiOS/pull/51.diff>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/DVT/ShowcaseiOS/pull/51>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ALgELqhQUwqg-treYzsJkTWkhDPy-UrNks5t2A-_gaJpZM4UOCZM>.
>

2018-05-27 18:58 UTC, pjwelcome requested changes

2018-05-27 18:58 UTC, pjwelcome commented on Showcase-iOS/Dashboard/Presenter/HomePresenter.swift
> +    func  transitionToShowcaseAppDetailView(with showcaseAppViewModel: ShowcaseAppViewModel) {
unit tests?

2018-05-28 13:14 UTC, pjwelcome approved these changes

2018-05-28 13:14 UTC, merged