Feature/user registration
DVT/ShowcaseiOS pull request #62
Opened 2018-05-29 14:22 UTC by Slavitor

This PR adds functionality that allows a user to register for DVT Showcase

2018-05-29 15:06 UTC, edward-mtsh commented on Showcase-iOS/Login/View/LoginNavigationController.swift
> +        loginViewController?.sharedApplication = SharedApplicationDelegateImplementation()
Lets make use of the container. Though will refactor it later.

let dependencyContainer = DependencyContainer.container()
loginViewController?.loginPresenter = dependencyContainer.resolve(LoginPresentable.self)
loginViewController?.sharedApplication = dependencyContainer.resolve(SharedApplicationDelegate.self)

2018-05-29 16:32 UTC, pjwelcome requested changes

2018-05-29 16:32 UTC, pjwelcome commented on Showcase-iOS/Login/Presenter/LoginPresenter.swift
> +    func openMailClient() {
unit tests?

2018-06-04 12:34 UTC, pjwelcome commented
@edward-mtsh Please can you look at this PR and fix the unit tests. Thank you

2018-06-08 11:12 UTC, pjwelcome approved these changes

2018-06-08 11:12 UTC, merged