Firebase Analytics - Contact us
DVT/ShowcaseiOS pull request #92
Opened 2019-04-01 09:46 UTC by Sashen943

- Analytic functions created in presenter and injected and implemented in View Controller
- Tests written for presenter
- General code clean up of contact us feature

2019-04-01 10:53 UTC, pjwelcome commented on Showcase-iOS/Contact Us/View/ContactUsViewController.swift
> +        let analyticManger = dependencyContainer.resolve(AnalyticsManager.self) as! AnalyticManagerImplementation
This is valid please fix this

2019-04-01 14:00 UTC, pjwelcome requested changes

2019-04-01 14:00 UTC, pjwelcome commented on Showcase-iOS/Contact Us/View/ContactUsViewController.swift
> +        contactUsPresenter?.trackScreenDidAppear(screen: "contact_us")
hard coded?

2019-04-01 14:16 UTC, Sashen943 commented on Showcase-iOS/Contact Us/View/ContactUsViewController.swift
> +        contactUsPresenter?.trackScreenDidAppear(screen: "contact_us")
fixed

2019-04-02 09:28 UTC, pjwelcome approved these changes

2019-04-02 09:29 UTC, merged