Firebase analytics - Login
DVT/ShowcaseiOS pull request #95
Opened 2019-04-02 11:06 UTC by Sashen943

- Analytics Manager added into presenter
- Functions in Presenter added to track analytics
- Injected into Login Navigation 
- Implemented in Login View Controller
- Tests added for new functionality in presenter
- General code clean up of login feature and tests:
>removed trailing white spaces
> added MARK comments
> refactored flow and renamed variables

2019-04-02 12:35 UTC, pjwelcome requested changes

2019-04-02 12:35 UTC, pjwelcome commented on Showcase-iOS/Login/View/LoginNavigationController.swift
> +            loginViewController?.sharedApplication = dependencyContainer.resolve(SharedApplicationDelegate.self)
This should not be inside this if let statement as it does not rely on login presenter

2019-04-02 20:15 UTC, Sashen943 commented on Showcase-iOS/Login/View/LoginNavigationController.swift
> +            loginViewController?.sharedApplication = dependencyContainer.resolve(SharedApplicationDelegate.self)
done :)

2019-04-02 20:18 UTC, Sashen943 commented on Showcase-iOS/Login/View/LoginViewController.swift
> +        self.showAlert(withTitle:  "Invalid inputs." ,
done

2019-04-02 20:18 UTC, Sashen943 commented on Showcase-iOS/Login/View/LoginNavigationController.swift
> +            if let analyticsManager = dependencyContainer.resolve(AnalyticsManager.self) as? AnalyticManagerImplementation {
done

2019-04-03 04:40 UTC, pjwelcome approved these changes

2019-04-03 04:45 UTC, merged